First revision of the Interval class. (#2417) (#2449)
* First revision of the Interval class.

* clang-format

* Add explicit default constructors to constexpr initializers for (empty) marker classes.

* clang-format

* A different ways of default-initializing

* Initialize marker classes in the header.

* GCC error fixes. Warnings still exist

* Add github action CI for new interval unit test (#2435)

* Fix compile on AppleClang 11

There was a bug in Clang's constexpr evaluator which causes this expression
to fail compilation [1]:

```
error: constexpr variable 'negative_infinity' must be initialized by a
      constant expression
  static constexpr T negative_infinity = -1 * std::numeric_limits<T>::infinity();
```

[1] https://reviews.llvm.org/D63793

* Add github action CI for new interval unit test

Co-authored-by: Isaiah Norton <isaiah@tiledb.io>

* Update comment style to be inline with rest of code

Co-authored-by: Seth Shelnutt <Shelnutt2@gmail.com>
Co-authored-by: Seth Shelnutt <seth@tiledb.io>
Co-authored-by: Isaiah Norton <isaiah@tiledb.io>

Co-authored-by: eric-hughes-tiledb <82400964+eric-hughes-tiledb@users.noreply.github.com>
Co-authored-by: Seth Shelnutt <Shelnutt2@gmail.com>
Co-authored-by: Seth Shelnutt <seth@tiledb.io>
Co-authored-by: Isaiah Norton <isaiah@tiledb.io>