Show errant values in current-domain out-of-bounds error message (#5421)
<long description>


[[sc-61579]](https://app.shortcut.com/tiledb-inc/story/61579/print-actual-coordinate-values-for-out-of-bounds-errors)

Before:

```
tiledbsoma._exception.SOMAError: [ManagedQuery] [unnamed] Query FAILED: Query: A range was set outside the current domain.
```

After:

```
tiledbsoma._exception.SOMAError: [ManagedQuery] [unnamed] Query FAILED: Query: A range [99999, 99999] on dimension 'soma_joinid' was set outside of the current domain [[0, 2637]].
```

---
TYPE: IMPROVEMENT
DESC: Show errant values in current-domain out-of-bounds error message