Include algorithm header for gcc 14. (#5139)
<long description>

There is a compilation error on gcc 14.
```
tiledb/sm/filesystem/posix.cc: In static member function ‘static void tiledb::sm::Posix::adjacent_slashes_dedup(std::string*)’:
tiledb/sm/filesystem/posix.cc:384:12: error: ‘unique’ is not a member of ‘std’
  384 |       std::unique(
      |            ^~~~~~
```
This patch will fix this issue.

---
TYPE: NO_HISTORY
DESC: Include <algorithm> header for gcc 14.

---------

Co-authored-by: Theodore Tsirpanis <theodore.tsirpanis@tiledb.com>
(cherry picked from commit 2eddec8a81ae9ceedd8246fbcd084f0cfa2ab7eb)