Bump Catch2 version to 2.13.8
Fixes build error in newer GCC versions due to changes in libc
const/constexpr definitions, see
`https://github.com/catchorg/Catch2/issues/2178` for details.

```
build/externals/src/ep_catch/single_include/catch2/catch.hpp:10822:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10822 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
```