CI: require test blocks to pass (doctest; png & cmake examples) (#1145)
* CI: require test blocks to pass (doctest; png & cmake examples)

Travis runs 'script' blocks with '-e', so intermediate command failures do not count as failing tests -- only the final exit status in a block is observed. Chaining blocks with '&&' propagates any failures in commands we care about.

* Remove unicode characters that made doc test fail

"""
ConfigError: There is a syntax error in your configuration file: Non-ASCII character '\xe2' in file /home/travis/build/TileDB-Inc/TileDB/doc/source/gensidebar.py on line 88, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details (gensidebar.py, line 88)
"""

* CI: fix build of PNG example on linux