Fix compile on AppleClang 11
There was a bug in Clang's constexpr evaluator which causes this expression
to fail compilation [1]:

```
error: constexpr variable 'negative_infinity' must be initialized by a
      constant expression
  static constexpr T negative_infinity = -1 * std::numeric_limits<T>::infinity();
```

[1] https://reviews.llvm.org/D63793