Fix Windows nighty builds. (#4300)
Fixes #4299, build failure on Windows due to warnings treated as errors:
```
D:\a\TileDB\TileDB\tiledb\sm\subarray\test\unit_range_subset.cc(376,32): error C2220: the following warning is treated as an error [D:\a\TileDB\TileDB\build\tiledb\tiledb\sm\subarray\test\unit_range_subset.vcxproj] 
```
---
TYPE: NO_HISTORY