S3 macOS CI fixes (#3642)
* S3 fixes

- Correct id for experimental CI target
- Update from deprecated minio environment variable names
- Fix AWS SDK build on new macOS w/ deprecated-declaration failures
- Add warning message when run-minio.sh not sourced

* Fix section

* Bind minio to 127.0.0.1 instead of localhost

    New Minio + macOS versions appear to have a problem binding to localhost
for unknown reasons:

```
Error: listen tcp 127.0.0.1:9999: bind: address already in use (*net.OpError)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/signals.go:79:cmd.handleSignals()
```

Binding to 127.0.0.1 appears to fix the problem.