Bind minio to 127.0.0.1 instead of localhost
New Minio + macOS versions appear to have a problem binding to localhost
for unknown reasons:

```
Error: listen tcp 127.0.0.1:9999: bind: address already in use (*net.OpError)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/signals.go:79:cmd.handleSignals()
```

Binding to 127.0.0.1 appears to fix the problem.