Fix Wunused-parameter failure due to capnp external code
Fixes errors like this from external dependency include:
"""
[ 86%] Building CXX object tiledb/CMakeFiles/TILEDB_CORE_OBJECTS.dir/sm/serialization/group.cc.o
In file included from /Users/runner/work/1/s/tiledb/sm/serialization/group.cc:35:
/Users/runner/work/1/s/build/externals/install/include/capnp/compat/json.h:367:40: error: unused parameter 'type' [-Werror,-Wunused-parameter]
                                  Type type, Orphanage orphanage) const override final {
"""